spring:
  application:
    name: pagamentos-ms
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL:jdbc:postgresql://0.0.0.0:55000/taberu-pagamento}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PWD:postgrespw}
    jpa:
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8081/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.int}

server:
  port: 0

resilience4j:
  circuitbreaker:
    instances:
      atualizaPedido:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s